### ISSUE TITLE
Point cache disappear at certain angles

### ISSUE THREAD

**Issue by melMass** [unity3d-jp/AlembicForUnity#115]
I'm trying to import point animation from Houdini using ABC Cache. Everything works as expected but for some reason some camera angles make the whole thing disappear... 
I've tried forcing occlusion culling but failed.

Is this a known issue ? Do you have any workaround ?

Thanks

**Comment by i-saint** [comment]
please keep in mind: we can't fix issues we can't reproduce.
if you want to fix the issue, send me the data that can reproduce the issue and Editor.log as issue template recommends.

**Comment by melMass** [comment]
Seems to be related to bounds. They aren't updated when using apply transform.

I'll PR when I have time.

Thanks
