### ISSUE TITLE
'AbcOnFrameChane' has no receiver error

### ISSUE THREAD

**Issue by ShawnFrueh** [unity3d-jp/AlembicForUnity#119]
AlembicForUnity: 20180413
Unity3D: 2018.1.3f1

When adding the imported alembics clip to the timeline or in the Animator Controller I get the following error. 

`'Name_Of_Alembic_File' AnimationEvent 'AbcOnFrameChange' has no receiver! Are you missing a component?`

**Comment by i-saint** [comment]
just use *_Time animation clip instead of *_Frames.

*_Frames clip contains AnimationEvents that is corresponding alembic's frame. you need to implement Components that implements AbcOnFrameChange() to handle events. see #71 for detailed info.

**Comment by ShawnFrueh** [comment]
Thank you!
