### ISSUE TITLE
Setting materials to the part/material name

### ISSUE THREAD

**Issue by ShawnFrueh** [unity3d-jp/AlembicForUnity#125]
AlembicForUnity: 20180413
Unity3D: 2018.1.3f1

When importing an Alembic file that has parts or materials. The correct material slots get added, however only one material gets made "Default Material."  Can we get an option to create a material per part and have it named accordingly? Similar to how FBX does so that materials already made that are the same name get applied correctly. 

Test Files: [https://www.dropbox.com/s/8okdzo73dxqmi7x/MaterialTest_Files.zip?dl=0](url)

**Comment by i-saint** [comment]
that is expected behavior and can't be improved because Alembic doesn't have material data.
