### ISSUE TITLE
Missing an assembly reference?

### ISSUE THREAD

**Issue by Quatro4** [unity3d-jp/AlembicForUnity#146]
Sorry if this is not the right place to ask this question, but I don't have much experience with code.

I managed to use the Alembic importer and everything works great inside Unity. However, when I try to create a build I get the following message:

Assets\UTJ\Alembic\Scripts\Timeline\AlembicShotAsset.cs(8,28): error CS0234: The type or namespace name 'DisplayName' does not exist in the namespace 'System.ComponentModel' (are you missing an assembly reference?)

Any suggestion on how I might solve it?

Thanks

**Comment by i-saint** [comment]
attach Editor.log as recommended, or nothing I can say.

**Comment by Quatro4** [comment]
[Editor.log](https://github.com/unity3d-jp/AlembicForUnity/files/2153407/Editor.log)

**Comment by i-saint** [comment]
I assume your target platform is Universal Windows Platform. it is not supported.
