### ISSUE TITLE
Crash by empty samples

### ISSUE THREAD

**Issue by i-saint** [unity3d-jp/AlembicForUnity#148]
https://issuetracker.unity3d.com/issues/unity-crashes-upon-converting-alembic-file-to-fbx
https://fogbugz.unity3d.com/f/cases/1032334/

the .abc file attached in above case contains empty samples. that causes a crash.
empty samples are quite unusual and neither Maya nor 3dsMax can't import it correctly, but Quill generates this sort of data...

**Comment by i-saint** [comment]
fixed in my local:
![screenshot 2018-07-05 02 06 10](https://user-images.githubusercontent.com/1488611/42290463-56efaebe-8000-11e8-926b-cc96bb581869.png)

**Comment by clusty** [comment]
fixed in 1.0.3
