### ISSUE TITLE
Unhandled native exception when running playmode tests in batch mode

### ISSUE THREAD

**Issue by mjmvisser** [unity3d-jp/AlembicForUnity#162]
To reproduce:
- check out markv/stable-katana-ci
- make sure you have a recent CMake in your path
- run build.cmd (windows) or build.sh (mac/linux)
- run Unity with these command-line arguments: -batchmode -projectPath path/to/repo/TestProjects/AlembicImporter/ -forgetProjectPath -automated -testResults path/to/repo/TestResults_playmode_AlembicImporter.xml -logFile path/to/repo/editor_playmode_AlembicImporter.log -runTests -testPlatform playmode

expected behaviour: tests pass, TestResults_playmode_AlembicImporter.xml is generated

actual behaviour: exception is raised, unity hangs (Mac) or crashes (Windows), TestResults_playmode_AlembicImporter.xml is not generated

stdout on Mac (I don't know how to see the stack trace on Windows):

> libc++abi.dylib: terminating with uncaught exception of type Alembic::Util::v10::Exception: No TimeSamples to write!
> Stacktrace:
> 
>   at (wrapper managed-to-native) UnityEngine.Formats.Alembic.Sdk.NativeMethods.aeDestroyContext (intptr) <IL 0x0000e, 0x000c2>
>   at (wrapper managed-to-native) UnityEngine.Formats.Alembic.Sdk.NativeMethods.aeDestroyContext (intptr) <IL 0x0000e, 0x000c2>
>   at UnityEngine.Formats.Alembic.Sdk.aeContext.Destroy () [0x00007] in /Users/markv/workspace/com.unity.formats.alembic/package/build/install/com.unity.formats.alembic/Runtime/Scripts/Exporter/AbcAPI.cs:261
>   at UnityEngine.Formats.Alembic.Util.AlembicRecorder.EndRecording () [0x00034] in /Users/markv/workspace/com.unity.formats.alembic/package/build/install/com.unity.formats.alembic/Runtime/Scripts/Exporter/AlembicExporter_impl.cs:980
>   at UnityEngine.Formats.Alembic.Exporter.AlembicExporter.EndRecording () [0x00007] in /Users/markv/workspace/com.unity.formats.alembic/package/build/install/com.unity.formats.alembic/Runtime/Scripts/Exporter/AlembicExporter.cs:75
>   at UnityEngine.Formats.Alembic.Exporter.AlembicExporter.OnDisable () [0x00002] in /Users/markv/workspace/com.unity.formats.alembic/package/build/install/com.unity.formats.alembic/Runtime/Scripts/Exporter/AlembicExporter.cs:123
>   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) <IL 0x0001c, 0x000f9>
> 

Note that opening the same project interactively and running tests (or just running the same command-line without "-batchmode") has no errors or exceptions. This seems to be a problem specific to batch mode.

**Comment by i-saint** [comment]
> opening the same project interactively and running tests has no errors or exceptions. This seems to be a problem specific to batch mode.
I think this means the problem is inside the test itself. re-assign me only when you are sure the problem is the plugin side. (I know nothing about test)

**Comment by i-saint** [comment]
if none of you work on it, I will resolve this issue by deleting the test.

**Comment by mjmvisser** [comment]
Update on this issue: @vkovec discovered that `yield return new WaitForEndOfFrame()` does not work in the editor in batch mode **by design**. The suggested solution is to exclude tests using this construct from all editor platforms with UnityPlatformAttribute.
