### ISSUE TITLE
alembic particles

### ISSUE THREAD

**Issue by hl2118** [unity3d-jp/AlembicForUnity#192]
hi, 
I am using the latest release of the alembic importer, trying to import particles point cloud generated from C4D thinking particles. while I checked to include the vertex color , it seems the importer could not recognize it and shows some pure white cubes. I wonder if there is a way I could retrieve the particle colors of the original particles, and be able to swap the cube to another geometry, or even unity particles?

**Comment by i-saint** [comment]
thanks for the report.
Alembic's Points schema doesn't have color property. so it is C4D-specific extension, which is not supported by this plugin. can you send me your .abc file? maybe I can investigate and add support.
