### ISSUE TITLE
Unity crashed when I import .abc files

### ISSUE THREAD

**Issue by ManyGueltonne** [unity3d-jp/AlembicForUnity#197]
Hi there,

I'm trying to use alembic importer but each times unity crashed.
All .abc files wont to work. The same files are working like a charm with UE4.
I 'm working with Unity 2018.2.8f1.

Here a log : 
[Editor.log](https://github.com/unity3d-jp/AlembicForUnity/files/2397534/Editor.log)

Thanks for the help

**Comment by i-saint** [comment]
attach .abc file that can reproduce the issue.

**Comment by ManyGueltonne** [comment]
.abc was generated by 3D Max 2k16.
[Files.zip](https://github.com/unity3d-jp/AlembicForUnity/files/2398400/Files.zip)

Thanks

**Comment by i-saint** [comment]
thanks. I wil work on it.

**Comment by ManyGueltonne** [comment]
Thank you : )

**Comment by i-saint** [comment]
I began to work on this issue. but your .abc files don't cause a crash. what version of package are you using?

**Comment by i-saint** [comment]
I assume your problem is solved by the latest package. if you still need help, add more information.

**Comment by ManyGueltonne** [comment]
Hello,
Sorry for the late answer.

The problem is not solved at all. Unity crash each time I import an .abc file. I donwloaded again the package, create a new project again, imported .abc and Unity crashed again.

**Comment by i-saint** [comment]
I'm asking what version of package you are using. latest github version (20180413) or packman version (0.1.2-preview)?

**Comment by i-saint** [comment]
if you are using latest github version and still crash, can you send me your project? minimal one that can reproduce the problem is ideal.

**Comment by ManyGueltonne** [comment]
You can find a screenshot about the version that I downloaded and the unity project.

![alembic](https://user-images.githubusercontent.com/24733856/46010623-ac7f9c00-c0c3-11e8-9ccb-ec4a4c736fc9.jpg)
[Unity  Alembic.zip](https://github.com/unity3d-jp/AlembicForUnity/files/2414905/Unity.Alembic.zip)

**Comment by i-saint** [comment]
download is right.
according to Editor.log, your project is located E: drive, can you try it on another drive?

**Comment by ManyGueltonne** [comment]
I created a new project on C drive, and Unity crashed again on imported .abc file : /

**Comment by i-saint** [comment]
I changed my system language to French, but I still couldn't reproduce the issue...
can you reinstall Unity to the default location and try again? I think it is unlikely it can solve your problem, but I don't have any other clues.

**Comment by ManyGueltonne** [comment]
Unity is installed on E Drive too. I don't have the time for now to reinstall the software, I working on project. I will try later. For this project I don't need alembic. Alembic works like a charm with UE4.

Thanks for the time that you offered to me ; )

**Comment by ManyGueltonne** [comment]
Nice, I will check this today : )
