### ISSUE TITLE
When deployed to a MacOS standalone app alembic shot clips do not play

### ISSUE THREAD

**Issue by kamyy** [unity3d-jp/AlembicForUnity#200]
[Editor.log](https://github.com/unity3d-jp/AlembicForUnity/files/2443146/Editor.log)

[Player.log](https://github.com/unity3d-jp/AlembicForUnity/files/2443131/Player.log)

[ADAM-AD3-0210_TheMirror_cloth.abc.zip](https://github.com/unity3d-jp/AlembicForUnity/files/2443134/ADAM-AD3-0210_TheMirror_cloth.abc.zip)

- Alembic shot clips do not play in the timeline when deployed to a MacOS standalone app. 
- I'm using MacOS High Sierra with OpenGL 4.1 enabled in Unity.
- Note, this problem does not occur on Windows with the same project.
- Note, the clips play as expected in the editor either by interacting with the timeline window or clicking the Play button.
- I'm using AlembicForUnity release 20180413.
- I'm using Unity 2018.2.10f1.

Looking at the player.log file this appears to be the problem:

Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./abci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/abci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.dylib
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.so
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/./libabci.bundle
Fallback handler could not load library /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/bb.app/Contents/Frameworks/MonoEmbedRuntime/osx/libabci
DllNotFoundException: abci
  at (wrapper managed-to-native) UTJ.Alembic.aiContext:aiContextCreate (int)
  at UTJ.Alembic.aiContext.Create (Int32 uid) [0x00002] in /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/Assets/UTJ/Alembic/Scripts/Importer/AbcAPI.cs:262 
  at UTJ.Alembic.AlembicStream.AbcLoad (Boolean createMissingNodes) [0x0001c] in /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/Assets/UTJ/Alembic/Scripts/Importer/AlembicStream.cs:124 
  at UTJ.Alembic.AlembicStreamPlayer.LoadStream (Boolean createMissingNodes) [0x00035] in /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/Assets/UTJ/Alembic/Scripts/Importer/AlembicStreamPlayer.cs:33 
  at UTJ.Alembic.AlembicStreamPlayer.OnEnable () [0x0000e] in /Users/kyip2/Work/tokyo-2020/tokyo-2020-unity/Assets/UTJ/Alembic/Scripts/Importer/AlembicStreamPlayer.cs:96

**Comment by kamyy** [comment]
Is there an ETA for a fix for this issue? I need to make plans to switch to something other than Alembic if this can't be resolved.

**Comment by i-saint** [comment]
ah, thanks for the followup.
