### ISSUE TITLE
Would it be possible to have an option to unlock normals? 

### ISSUE THREAD

**Issue by ShawnFrueh** [unity3d-jp/AlembicForUnity#205]
I've noticed that some alembic files have locked normals (Not sure if that is just an alembic thing). Is it possible to have an option to force normals to be unlocked?

**Comment by i-saint** [comment]
I'm not sure what "locked normals" means.
if you mean normals are not animated and want "calculate normals at runtime" options, it is possible but I don't want to do it. in such case, what should be fixed is .abc file itself and it should be done in DCC side.
