### ISSUE TITLE
Alembic file UV2 data is not correct

### ISSUE THREAD

**Issue by Derson2389** [unity3d-jp/AlembicForUnity#222]
I export ABC file from Maya 2018 with Muti UV Set ,  but import in Unity, I found the UV2 Data is wrong , seems there is no data vlaue in UV2

**Comment by Derson2389** [comment]
my abc file is too big can not attach

**Comment by Derson2389** [comment]
[cha_cloth_v00x.zip](https://github.com/unity3d-jp/AlembicForUnity/files/2706587/cha_cloth_v00x.zip)

**Comment by Derson2389** [comment]
add the abc file ,please check . Thanks!

**Comment by i-saint** [comment]
you mean 3rd channel of UV? it is not supported because 3rd and 4th uv channel are internally used in some cases. Unity 2018.x supports 8 channels of UV, so possibly we support more UV channels. but I'm not sure when it will be done.
