### ISSUE TITLE
Alembic files using alembic stream player do not show up in builds

### ISSUE THREAD

**Issue by lordvard** [unity3d-jp/AlembicForUnity#284]
Version via Package Manager: 1.0.5, Unity version 2019.1.14f

My project uses three alembic files with alembic stream player and animations. they work perfectly in the editor, but in builds they disappear.

Files do not show up in the StreamingAssets folder.

Have tried copying the files into the StreamingAssets folder before building, the files then appear in the build's StreamingAsset folder the models/animations do not show up in the build.

**Comment by clusty** [comment]
Hey,
What platform are you running the editor and what player are you trying to build ?
Are the files present in the scenes at the time of the build or are they dynamically spawned ?
This should work under Windows and OSX.

**Comment by lordvard** [comment]
Hi, 
I am running Windows x64 in the editor and trying to build to the same platform. 
The files are present in the scene, not dynamically spawned. 
I made it work once yesterday, but the problem keeps returning.

**Comment by clusty** [comment]
Had another idea: are the GameObjects disabled by chance at the time of build?
I found a bug related to that today.

**Comment by JohannesDeml** [comment]
Maybe my pipeline script helps you copying the alembics correctly (with their relative path). https://forum.unity.com/threads/missing-alembic-streaming-assets.635320/#post-4776968

It also runs automated after each build, so there is less room for errors :)

**Comment by cguer** [comment]
Similar issue is resolved in 1.0.6.  Missing steps to reproduce described issue.  Closing issue for now and will re-open if it comes up again.

**Comment by clusty** [comment]
> Had the same Issue again. I was not able to build the game to android while using the alembic stream. Unity 2021.3.1f1

Android is not supported unfortunately, only desktop standalone builds.
