### ISSUE TITLE
AlembicShotAssets are played out of sync with FBX AnimationClips

### ISSUE THREAD

**Issue by Chosko** [unity3d-jp/AlembicForUnity#84]
Version used: 20180320

In my project, I have animated objects that have some parts made in FBX and other parts in Alembic.

I put both the FBX and Alembic animations in a Timeline, in sync. But, during playback, the Alembic parts are always updated (or rendered?) with a delay.
This small delay is often unnoticeable, but it becomes really visible in case of faster movements, and in my case the outcome is really bad.

I made some investigations. That's what I found:

I'm sure it is not a simple sync issue between the clips in timeline. I also tried moving them several times without finding a solution. 
Moreover, when I run the timeline frame by frame (using the "Go to the next frame" button in the Timeline window), I see that the FBX suddenly updates, while the Alembic sometimes updates with a delay and other times doesn't even update until I resize the Scene window (thus forcing an update).

I'm attaching a sample project in which the issue is visible. There is an Alembic rope with an FBX hook at the end. Please try to run the timeline frame by frame, forward. You should see something similar to this:

![rope-forward](https://user-images.githubusercontent.com/3297850/37767492-a3c24e14-2dca-11e8-9704-5663f6991b21.PNG)

If you go a frame backward you should see this:

![rope-backward](https://user-images.githubusercontent.com/3297850/37767790-9a3ec7cc-2dcb-11e8-8225-f70e9e201e84.PNG)

The rope and the hook are inverted.. this means that the delay always occur, no matter if you are going forward or backward, and I can't workaround this issue rearranging the clips in the timeline, because the size of the gap does not depend on the framerate of the timeline but on the framerate of the game...

Finally, if you just play the project, you'll see this issue in motion, which depends on game frame-rate.
I added a speed multiplier of 2.0f to the clips to help visualize it.

[AlembicSyncTestProject.zip](https://github.com/unity3d-jp/AlembicImporter/files/1837246/AlembicSyncTestProject.zip)

**Comment by i-saint** [comment]
thanks for the report.

this is update-order issue (update alembic animation _before_ timeline update) and you can fix it by this simple change da941da.
I will test it further and include this fix in next release.

**Comment by Chosko** [comment]
Thank you for the fix.
BTW, In this way the update is called twice, isn't it?

**Comment by i-saint** [comment]
true. but updating animation and mesh is skipped if time is not changed. so overhead is almost ignorable.

**Comment by Chosko** [comment]
Ah, great! Thank you

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicForUnity/releases/tag/20180413

**Comment by ShawnFrueh** [comment]
Still getting this bug in 20180413. Tried multiple frame Rates but no luck. In software(MODO) the two line up just fine. But when split FBX and alembic. Alembic doesn't seem to update every frame of the timeline. I manually keyed the time on the player but still no luck.

**Comment by i-saint** [comment]
@ShawnFrueh send me data to reproduce the issue. otherwise, I can do nothing.

**Comment by ShawnFrueh** [comment]
Here's a zipped project 22MB: https://bit.ly/2vbLmMs

**Comment by i-saint** [comment]
@ShawnFrueh thanks. but nothing happens when I load and play your project. TimeLine is empty and everything is still. can you revise the project? also, I want screenshots that point what is expected (MODO side) and what is the problem (Unity side).
![screenshot 2018-08-02 07 24 32](https://user-images.githubusercontent.com/1488611/43552547-dba5e98a-9625-11e8-84b5-2b9f5b48142a.png)

**Comment by ShawnFrueh** [comment]
Strange, I've updated the project to 2018.1.3f1 and repackaged the project. 
Project, same filename: https://bit.ly/2vbLmMs
Here are comparison gifs:
In MODO
![alembicfbx_inmodo](https://user-images.githubusercontent.com/6474667/43587286-7d494ab2-962f-11e8-8f81-410fc07cdb1a.gif)
In Unity
![alembicfbx_inunity](https://user-images.githubusercontent.com/6474667/43587287-7d599cbe-962f-11e8-8dac-c7a85b78c207.gif)

Timeline incase it doesnt show again:
![alembicfbx_timeline](https://user-images.githubusercontent.com/6474667/43587428-d5784062-962f-11e8-81e7-0a6208d97324.PNG)

**Comment by i-saint** [comment]
thanks. I confirmed the issue. and these screenshots are very helpful. I'm working on it.

**Comment by ShawnFrueh** [comment]
I did a little more digging around today and found out that the issue is with the timeline FPS being higher/different than the Alembic FPS. When set the timeline to 30FPS (The fps of the abc file) everything seem to run as expected. However changing the timeline FPS to 60(default) the alembic file struggles. Even with interpolation enabled.
