### ISSUE TITLE
maxのカメラの傾きがUnityに反映されない

### ISSUE THREAD

**Issue by KiTiGOE** [unity3d-jp/AlembicForUnity#85]
3dsMax側のカメラの傾きがUnity側に反映されません。
Max側でカメラを地平線に対しいくらか傾けてAlembic形式でUnityに送ると、Unityでは地平線に対しカメラが平行になった状態で読み込まれるのです。
![default](https://user-images.githubusercontent.com/34207039/37909425-d8477500-3145-11e8-9c05-37fc088b04a5.png)
もしかしたらAlembicという形式のそもそもの性質なのかもしれないのですが、不自然だと思い相談しました。
どなたかこの現象についてお分かりになりますでしょうか？

状況が再現できるZipファイルを添付します。
少しでも参考になれば幸いです。

[max to unity camera bug.zip](https://github.com/unity3d-jp/AlembicImporter/files/1848018/max.to.unity.camera.bug.zip)

**Comment by i-saint** [comment]
レポートありがとうございます。

Alembic のカメラは Unity のカメラとは前後が逆転してるんですが、それを正す際に意図せず傾きも無効化しているバグがありました。
このパッケージだと問題ないと思うんですが、よろしければ試していただけますでしょうか。(問題なければ正式に次のリリースに含めます)
[AlembicForUnity.zip](https://github.com/unity3d-jp/AlembicImporter/files/1849868/AlembicForUnity.zip)

**Comment by KiTiGOE** [comment]
迅速な対応本当にありがとうございます！
手元で試してみた所、問題なく傾きが保持されていました。

いつも本当にありがとうございます。

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicForUnity/releases/tag/20180413
