### ISSUE TITLE
Crash when trying to scrub the "time parameter" in the inspector

### ISSUE THREAD

**Issue by Supaworst** [unity3d-jp/AlembicForUnity#88]
Hello,
as the title says i'm having a crash when trying to preview the animation by scrubbing the time parameter in the inspector tab. 
Even changing the value from 0 to anything else will reproduce the issue.

Some extra info:

The file was generated with blender 2.79 starting from particles that i've remeshed with an addon (cubesurfer) that basically uses a blender isosurface. 

The package version is 20180320 donwloaded yesterday.

I'm attaching you also the file with the edito log:

[Editor.log](https://github.com/unity3d-jp/AlembicImporter/files/1859898/Editor.log)
[Slime.zip](https://github.com/unity3d-jp/AlembicImporter/files/1859900/Slime.zip)

Anyway, thanks for this plugin!

**Comment by i-saint** [comment]
thanks for the report.

this is almost same issue as #81. basically Blender's issue.
Blender's alembic exporter generates invalid alembic file if mesh topology changes over time. in this case uv param is invalid except first frame. (in case #81 vertex color param was invalid)
I will add workaround to try to avoid crash. but you may see unexpected result because this .abc has invalid data.

**Comment by Supaworst** [comment]
Thanks a lot, in any case, at the moment, i'm not going to have uv/vcolors problem  because i'm using a triplanar shader so i don't need them.

Thanks again, i'll definitely give it a try.

**Comment by i-saint** [comment]
in that case, I think disabling uv, normals and vertex color export can solve your problem.

**Comment by Supaworst** [comment]
Just tried and it works perfectly, thanks!

Anyway, i'm having a problem building for webGL, basically, while testing it with the browser, the debug says that a .ddl is missing. 

Should i have to open another issue ticket?

**Comment by i-saint** [comment]
as explained in documents, this plugin supports desktop platforms only (Windows, Mac, Linux).

**Comment by Supaworst** [comment]
Sorry, i really missed that part. Any plan to support other platforms in the future?

**Comment by i-saint** [comment]
it is planned, but not come soon. if everything go well, probably come in early next year.

**Comment by i-saint** [comment]
https://github.com/unity3d-jp/AlembicForUnity/releases/tag/20180413
