### ISSUE TITLE
Meshes should not been saved into scene

### ISSUE THREAD

**Issue by shiyamon** [unity3d-jp/AlembicForUnity#95]
A scene file with abs assets becomes very large because of dynamic meshes saved in scene file.
I guess these meshes don't need to be saved in scene file because iIt seems abs meshes are loaded on scene load and updated on runtime anyway.

I tried adding

mesh.hideFlags = HideFlags.DontSaveInEditor

to AddMeshComponents() method in AlembicMesh class and found now scene file got smaller.
Do you think this workaround would cause any side effects?

**Comment by i-saint** [comment]
good point. I will test and apply your suggestions if there is no problem.
thanks for your feedback!

**Comment by clusty** [comment]
Fixed in 1.0.0+
